version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: flashcards-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: a
      POSTGRES_DB: flashcards
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - flashcards-network

  adminer:
    image: adminer:latest
    container_name: flashcards-adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - flashcards-network

volumes:
  postgres-data:
    driver: local

networks:
  flashcards-network:
    driver: bridge
